package com.lambda.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName = "cc_tests")
@DynamoDBDocument
public class Test {

    private String testUUID;
    private List<Question> questions;
    private User user;
    private String name;
    private String lang;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getTestUUID() {
        return testUUID;
    }

    public void setTestUUID(String testUUID) {
        this.testUUID = testUUID;
    }

    public void setQuestions(List<Question> questions) {
        this.questions = questions;
    }

    public List<Question> getQuestions() {
        return questions;
    }
    
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @DynamoDBAttribute(attributeName = "lang")
    public String getLang() {
        return lang;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    @DynamoDBIgnore
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
